---
driver:
  name: docker
  hostname: debmirror.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false
  build_options:
    build-arg: --ulimit nofile=4096:8192 # debmirror req

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: debmirror
  log_level: info
  state_top:
    base:
      "*":
        - debmirror
  pillars:
    top.sls:
      base:
        "*":
          - debmirror
  grains:
    noservices: True

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

verifier:
  name: inspec
  sudo: true

suites:
  - name: debmirror-client
    provisioner:
      pillars-from-files:
        debmirror.sls: tests/pillar/client.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
